name: API Automation Tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  cypress-api-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout projeto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes Cypress
        run: npx cypress run

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-report
          path: cypress/reports